/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlumnsPage: typeof import('./pages/AlumnsPage.vue')['default']
    BlankLayout: typeof import('./layouts/BlankLayout.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    HomePage: typeof import('./pages/HomePage.vue')['default']
    LoginPage: typeof import('./pages/LoginPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
